---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: ingress-gateway-abc
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: abc
  name: ingress-abc
spec:
  displayName: IngressGW_ABC
  http:
    - hostname: abc.demo.tetrate.io
      name: ingress-abc-http
      port: 80
      routing:
        rules:
          - route:
              host: ns-a/app-a.ns-a.svc.cluster.local
              port: 80
    - hostname: abc-https.demo.tetrate.io
      name: ingress-abc-https
      port: 443
      tls:
        mode: SIMPLE
        secretName: abc-https-cert
      routing:
        rules:
          - route:
              host: ns-a/app-a.ns-a.svc.cluster.local
              port: 80
    - hostname: abc-mtls.demo.tetrate.io
      name: ingress-abc-mtls
      port: 443
      tls:
        mode: MUTUAL  
        secretName: abc-mtls-cert
      routing:
        rules:
          - route:
              host: ns-a/app-a.ns-a.svc.cluster.local
              port: 80
  workloadSelector:
    labels:
      app: gw-ingress-abc
    namespace: gateway-abc