---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-d
  name: sa-app-d
  namespace: ns-d
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-e
  name: sa-app-e
  namespace: ns-e
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-f
  name: sa-app-f
  namespace: ns-f