---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-d
    version: v1
  name: app-d-v1
  namespace: ns-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-d
      version: v1
  template:
    metadata:
      labels:
        app: app-d
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-d
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-e
    version: v1
  name: app-e-v1
  namespace: ns-e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-e
      version: v1
  template:
    metadata:
      labels:
        app: app-e
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-e
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-f
    version: v1
  name: app-f-v1
  namespace: ns-f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-f
      version: v1
  template:
    metadata:
      labels:
        app: app-f
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-f
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-f