---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: gw-ingress-def
  namespace: ingress-def
spec:
  eastWestOnly: false
  kubeSpec:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: tetrate:owner=bart,tetrate:team=sales:se,tetrate:purpose=poc,tetrate:lifespan=ongoing,tetrate:customer=coindcx
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      type: LoadBalancer