---
apiVersion: install.tetrate.io/v1alpha1
kind: Tier1Gateway
metadata:
  name: gw-tier1-ghi
  namespace: tier1-ghi
spec:
  kubeSpec:
    overlays:
      - apiVersion: apps/v1
        kind: Deployment
        name: gw-tier1-ghi
        patches:
          - path: spec.template.spec.containers
            value:
              - args:
                  - run
                  - '--server'
                  - '--addr=localhost:8181'
                  - '--diagnostic-addr=0.0.0.0:8282'
                  - '--set=plugins.envoy_ext_authz_grpc.addr=:9191'
                  - '--set=plugins.envoy_ext_authz_grpc.query=data.demo.basicauth.allow'
                  - '--set=decision_logs.console=true'
                  - '--ignore=.*'
                  - /policy/policy.rego
                image: openpolicyagent/opa:latest-envoy
                livenessProbe:
                  httpGet:
                    path: /health?plugins
                    port: 8282
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 5
                name: opa
                readinessProbe:
                  httpGet:
                    path: /health?plugins
                    port: 8282
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 5
                securityContext:
                  runAsUser: 1111
                volumeMounts:
                  - mountPath: /policy
                    name: opa-policy
                    readOnly: true
          - path: spec.template.spec.volumes
            value:
              - configMap:
                  name: opa-basicauth-policy
                name: opa-policy
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: tetrate:owner=bart,tetrate:team=sales:se,tetrate:purpose=poc,tetrate:lifespan=ongoing,tetrate:customer=coindcx
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      type: LoadBalancer