---
apiVersion: v1
kind: Service
metadata:
  name: opa-tier1-ghi
  namespace: tier1-ghi
spec:
  ports:
    - name: grpc
      port: 9191
      protocol: TCP
      targetPort: 9191
  selector:
    app: opa-tier1-ghi