---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-a
    version: v1
  name: app-a-v1
  namespace: ns-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
      version: v1
  template:
    metadata:
      labels:
        app: app-a
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-a
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-b
    version: v1
  name: app-b-v1
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
      version: v1
  template:
    metadata:
      labels:
        app: app-b
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-b
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-c
    version: v1
  name: app-c-v1
  namespace: ns-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-c
      version: v1
  template:
    metadata:
      labels:
        app: app-c
        version: v1
    spec:
      containers:
        - args:
            - '--log-output-level=all:debug'
            - '--http-listen-address=:8000'
            - '--tcp-listen-address=:3000'
            - '--ep-duration=0'
            - '--ep-errors=0'
            - '--ep-headers=0'
            - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
            - '--zipkin-sample-rate=1.0'
            - '--zipkin-singlehost-spans'
          env:
            - name: SVCNAME
              value: app-c
          image: $ECR_REPO_URL/obs-tester-server:1.0
          imagePullPolicy: IfNotPresent
          name: obs-tester
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 3000
              name: tcp
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
      serviceAccountName: sa-app-c