---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsb-admin
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tsb
    repoURL: $GITEA_PUBLIC_URL/gitea-admin/tsb-admin.git
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
      limit: 10