---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-a
  name: sa-app-a
  namespace: ns-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-b
  name: sa-app-b
  namespace: ns-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-c
  name: sa-app-c
  namespace: ns-c