---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: ingress-gateway-ghi
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: ghi
  name: ingress-ghi
spec:
  displayName: IngressGW_GHI
  http:
    - hostname: ghi.demo.tetrate.io
      name: ghi-http
      port: 80
      routing:
        rules:
          - route:
              host: ns-g/app-g.ns-g.svc.cluster.local
              port: 80
    - hostname: ghi-https.demo.tetrate.io
      name: ghi-https
      port: 443
      routing:
        rules:
          - route:
              host: ns-g/app-g.ns-g.svc.cluster.local
              port: 80
      tls:
        mode: SIMPLE
        secretName: ghi-https-cert
    - hostname: ghi-mtls.demo.tetrate.io
      name: ghi-mtls
      port: 443
      routing:
        rules:
          - route:
              host: ns-g/app-g.ns-g.svc.cluster.local
              port: 80
      tls:
        mode: MUTUAL
        secretName: ghi-mtls-cert
  workloadSelector:
    labels:
      app: gw-ingress-ghi
    namespace: ingress-ghi