---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/securityGroup: security-g
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: ghi
  name: ingress-to-g
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
        - from:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-ingress-ghi
          to:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-g
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/securityGroup: security-h
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: ghi
  name: g-to-h
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
        - from:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-g
          to:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-h
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/securityGroup: security-i
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: ghi
  name: h-to-i
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
        - from:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-h
          to:
            fqn: organizations/tetrate/tenants/prod/workspaces/ghi/securitygroups/security-i