---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: lambda-tetrate1
  namespace: ingress-lambda
spec:
  hosts:
    - $HELLO_LAMBDA_URL
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: lambda-tetrate2
  namespace: ingress-lambda
spec:
  hosts:
    - $GREETINGS_LAMBDA_URL
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS