---
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
  name: lambda
spec:
  displayName: WorkSpace_Lambda
  namespaceSelector:
    names:
      - mgmt/tier1-lambda
      - active/ingress-lambda
