---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: lambda
  name: tier1-gateway-lambda
spec:
  configMode: BRIDGED
  displayName: Tier1Gateway_Lambda
  namespaceSelector:
    names:
      - mgmt/tier1-lambda
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: lambda
  name: ingress-gateway-lambda
spec:
  configMode: BRIDGED
  displayName: IngressGateway_Lambda
  namespaceSelector:
    names:
      - active/ingress-lambda
