---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: tier1-gateway-lambda
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: lambda
  name: tier1-lambda
spec:
  displayName: Tier1GW_Lambda
  externalServers:
    - clusters:
        - name: active
      hostname: lambda.demo.tetrate.io
      name: lambda-http
      port: 80
    - clusters:
        - name: active
      hostname: lambda-https.demo.tetrate.io
      name: lambda-https
      port: 443
      tls:
        mode: SIMPLE
        secretName: lambda-https-cert
    - clusters:
        - name: active
      hostname: lambda-mtls.demo.tetrate.io
      name: lambda-mtls
      port: 443
      tls:
        mode: MUTUAL
        secretName: lambda-mtls-cert
  workloadSelector:
    labels:
      app: gw-tier1-lambda
    namespace: tier1-lambda