---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: ingress-gateway-lambda
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: lambda
  name: ingress-lambda
spec:
  displayName: IngressGW_Lambda
  http:
    - hostname: lambda.demo.tetrate.io
      name: lambda-http
      port: 80
      routing:
        rules:
          - route:
              host: ingress-lambda/62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
              port: 443
            modify:
              rewrite:
                authority: 62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
    - hostname: lambda-https.demo.tetrate.io
      name: lambda-https
      port: 443
      tls:
        mode: SIMPLE
        secretName: lambda-https-cert
      routing:
        rules:
          - route:
              host: ingress-lambda/62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
              port: 443
            modify:
              rewrite:
                authority: 62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
    - hostname: lambda-mtls.demo.tetrate.io
      name: lambda-mtls
      port: 443
      tls:
        mode: MUTUAL
        secretName: lambda-mtls-cert
      routing:
        rules:
          - route:
              host: ingress-lambda/62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
              port: 443
            modify:
              rewrite:
                authority: 62dskax6mej2sssbvnh2j2uile0rbmfb.lambda-url.eu-west-1.on.aws
  workloadSelector:
    labels:
      app: gw-ingress-lambda
    namespace: ingress-lambda