---
apiVersion: traffic.tsb.tetrate.io/v2
kind: TrafficSetting
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/trafficGroup: traffic-e
    tsb.tetrate.io/workspace: def
  name: e-to-egress
spec:
  egress:
    host: egress-def/gw-egress-def.egress-def.svc.cluster.local
  reachability:
    hosts:
      - active/ns-e
    mode: CUSTOM