---
apiVersion: tsb.tetrate.io/v2
kind: Cluster
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
  name: mgmt
spec:
  locality:
    region: eu-west-1
  network: tier1
  tier1Cluster: true
  tokenTtl: 31536000s
---
apiVersion: tsb.tetrate.io/v2
kind: Cluster
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
  name: active
spec:
  locality:
    region: eu-west-1
  network: tier2
  tier1Cluster: false
  tokenTtl: 31536000s
---
apiVersion: tsb.tetrate.io/v2
kind: Cluster
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
  name: standby
spec:
  locality:
    region: eu-west-2
  network: tier2
  tier1Cluster: false
  tokenTtl: 31536000s